# Generated by Django 4.2.2 on 2024-08-29 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Advertência', 'Advertência'), ('Advertência Escrita', 'Advertência Escrita'), ('Horas Orientadas', 'Horas Orientadas'), ('Suspensão', 'Suspensão'), ('Perda Residência', 'Perda Residência'), ('Expulsão', 'Expulsão')], max_length=100, verbose_name='Descrição')),
                ('classification', models.CharField(choices=[('L', 'Leve'), ('M', 'Média'), ('G', 'Grave')], max_length=1, verbose_name='Classificação')),
                ('ata', models.CharField(blank=True, max_length=50, verbose_name='Registro Ata')),
            ],
            options={
                'verbose_name': 'Medida Disciplinar',
                'verbose_name_plural': 'Medidas Disciplinares',
            },
        ),
        migrations.CreateModel(
            name='Regulations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulation', models.CharField(blank=True, max_length=50, verbose_name='Regulamentação')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descrição da regra')),
                ('psychologist', models.CharField(blank=True, max_length=100, verbose_name='Psicóloga')),
                ('pedagogue', models.CharField(blank=True, max_length=100, verbose_name='Pedagogo')),
                ('coordinatordae', models.CharField(blank=True, max_length=100, verbose_name='Coordenador DAE')),
                ('coordinatorres', models.CharField(blank=True, max_length=100, verbose_name='Coordenador Residencia')),
                ('director', models.CharField(blank=True, max_length=100, verbose_name='Diretor')),
            ],
            options={
                'verbose_name': 'Regulamento',
                'verbose_name_plural': 'Regulamento',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=20, verbose_name='Matrícula do aluno')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do aluno')),
                ('namefather', models.CharField(max_length=100, null=True, verbose_name='Nome do Pai')),
                ('telfather', models.CharField(max_length=100, null=True, verbose_name='Telefone do Pai')),
                ('namemother', models.CharField(max_length=100, null=True, verbose_name='Nome da Mãe')),
                ('telmother', models.CharField(max_length=100, null=True, verbose_name='Telefone da Mãe')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='Email Responsável')),
                ('genre', models.CharField(choices=[('', 'Não informado'), ('M', 'MASCULINO'), ('F', 'FEMININO'), ('O', 'OUTRO')], max_length=50, null=True, verbose_name='Gênero')),
                ('birth_date', models.DateField(null=True, verbose_name='Data de nascimento')),
                ('career', models.CharField(choices=[('TAGRO', 'TAGRO'), ('TMSI', 'TMSI')], max_length=20, null=True, verbose_name='Curso')),
                ('risk_knn', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='KNN - K-Nearest Neighbour')),
                ('risk_skl', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='SKL - Naive Bayes')),
                ('risk_tree', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Árvore de decisão')),
                ('risk_mlp', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='MLP - Multi Layer Perceptron')),
            ],
            options={
                'verbose_name': 'Estudante',
                'verbose_name_plural': 'Estudantes',
            },
        ),
        migrations.CreateModel(
            name='Violations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500, verbose_name='Descrição da ocorrência')),
                ('complement', models.CharField(max_length=255, null=True, verbose_name='Complemento da medida disciplinar')),
                ('date_event', models.DateField(verbose_name='Data do evento')),
                ('measure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='knnapp.measures', verbose_name='Medida disciplinar')),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='knnapp.regulations', verbose_name='Infração')),
                ('student', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='knnapp.students', verbose_name='Estudante')),
            ],
            options={
                'verbose_name': 'Violação',
                'verbose_name_plural': 'Violações',
            },
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='knnapp.measures', verbose_name='Medida disciplinar')),
                ('regulations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='knnapp.regulations', verbose_name='Regulamentos')),
                ('student', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='knnapp.students', verbose_name='Estudante')),
            ],
            options={
                'verbose_name': 'Recomendação',
                'verbose_name_plural': 'Recomendações',
            },
        ),
        migrations.AddField(
            model_name='measures',
            name='regulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='knnapp.regulations', verbose_name='Regulamento'),
        ),
    ]
